services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: legal-benchmark-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "LegalBenchmark!2024"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - legal-benchmark-sqldata:/var/opt/mssql
volumes:
  legal-benchmark-sqldata:
